version: 2.1

executors:
  default:
    docker:
      - image: cimg/python:3.8

orbs:
  set-env-var:
    version: 1.0.3
    source: shandlitest/set-env-var

jobs:
  check_started_by:
    executor: default
    steps:
      - checkout

      # Fetch the workflow information to get the started_by
      # - run:
      #     name: Install jq
      #     command: |
      #       sudo apt-get update && sudo apt-get install -y jq

      # Fetch the workflow information to get the `started_by`
      - run:
          name: Get Workflow Info
          command: |
            WORKFLOW_ID=${CIRCLE_WORKFLOW_ID}
            echo "Workflow ID: ${WORKFLOW_ID}"  # Print the workflow ID for debugging

            WORKFLOW_INFO=$(curl -s -H "Circle-Token: ${CIRCLE_TOKEN}" "https://circleci.com/api/v2/workflow/${WORKFLOW_ID}")
            echo "Workflow Info: ${WORKFLOW_INFO}"  # Print the workflow info for debugging

            # Parse `started_by` email from the workflow info
            STARTED_BY_UUID=$(echo "$WORKFLOW_INFO" | jq -r '.started_by')
            echo "Started By: ${STARTED_BY_UUID}"  # Print started_by for debugging

            # Add started_by to the environment
            echo "STARTED_BY_UUID=${STARTED_BY_UUID}" >> $BASH_ENV

            # STARTED_BY=$(curl -s -H "Circle-Token: ${CIRCLE_TOKEN}" "https://circleci.com/api/v2/user/${STARTED_BY_UUID}")
            echo "Extracted circle token: ${CIRCLE_TOKEN}"
            STARTED_BY=$(curl -s -H "Circle-Token: ${CIRCLE_TOKEN}" "https://circleci.com/api/v2/user/${STARTED_BY_UUID}")
            echo "User Info: ${STARTED_BY}"  # Print user info for debugging

            # Extract `name` from user info
            STARTED_BY=$(echo "$STARTED_BY" | jq -r '.name')
            echo "STARTED_BY=${STARTED_BY}" >> $BASH_ENV
            echo "Extracted user name: ${STARTED_BY}"
      - run:
          name: Run Conditional Steps
          command: |
            if [ "$STARTED_BY" == "qdbrowserstack@gmail.com" ]; then
              echo "User is qdbrowserstack@gmail.com, running orb command"
              # Call the orb command with specific parameters
              # - set-env-var/greet
              # # Set the environment variable
              # #echo "CUSTOM_ENV_VAR=custom_value" >> $BASH_ENV
            else
              echo "User is not qdbrowserstack@gmail.com, setting default values"
              # Set default values if the condition is not met
              echo "ANOTHER_VAR='fatal'" >> $BASH_ENV
            fi
            
      - when:
          condition:
            equal: ["qdbrowserstack@gmail.com", "${STARTED_BY}"]
          steps:
            - set-env-var/greet
            
      - run:
          name: Print Final Variable Value
          command: |
            source $BASH_ENV
            echo "Final value of CUSTOM_ENV_VAR: ${ANOTHER_VAR}"


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - check_started_by
      - deploy:
          requires:
            - check_started_by
            
