version: 2.1

executors:
  default:
    docker:
      - image: cimg/python:3.8

orbs:
  set-env-var: shandlitest/set-env-var@1.0.5

jobs:
  check_started_by:
    executor: default
    steps:
      - checkout
      - run:
          name: Print Final Variable Value
          command: |
            echo 'export ANOTHER_VAR="I got the answer"'>> "$BASH_ENV"
      - set-env-var/greet
            
      - run:
          name: Print Final Variable Value
          command: |
            source $BASH_ENV
            echo "Final value of CUSTOM_ENV_VAR: ${ANOTHER_VAR}"

  # orb_job:
  #   executor: default
  #   steps:
  #     - when:
  #         condition:
  #           equal: ["$STARTED_BY", "qdbrowserstack@gmail.com"]
  #         steps:
  #           - set-env-var/greet

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - check_started_by
      # - orb_job:
      #     requires:
      #       - check_started_by

